# Generated by Django 4.1.2 on 2022-12-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('especialidad', models.CharField(max_length=25)),
                ('evaluacion_doc', models.IntegerField()),
                ('horario_atencion', models.DateTimeField()),
                ('disponible', models.BooleanField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad_paciente', models.IntegerField()),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='HorasMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horaMed', models.DateTimeField()),
                ('valor_hora', models.IntegerField()),
                ('doctor_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
            options={
                'db_table': 'horas_medicos',
            },
        ),
    ]
