# Generated by Django 4.1 on 2022-12-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_url_imagen_doctor_url_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="url_image",
            new_name="url_imagen",
        ),
    ]
