# Generated by Django 4.1 on 2022-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_url_image_doctor_url_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="evaluacion_doc",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
